development:
  adapter: postgresql
  encoding: unicode
  database: hangman-web_development
  pool: 5
  username: hangman-web
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hangman-web_test
  pool: 5
  username: hangman-web
  password: